apiVersion: batch/v1
kind: Job
metadata:
  name: integration-testing
spec:
  template:
    spec:
      containers:
      - name: integration-testing
        image: timetablerapi-integration-testing
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgres://testuser:testpassword@postgres:5432/testdb?sslmode=disable"
      restartPolicy: Never
  backoffLimit: 3
